sudo: required

language: python

services:
    - docker

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

install:
    # From https://docs.codecov.io/docs/testing-with-docker
    - mkdir shared
    - docker build -t pycondor_docker -f ci/Dockerfile --build-arg python_version=${TRAVIS_PYTHON_VERSION} .
    - docker run -d --name test_container -v "$PWD/shared:/shared" pycondor_docker
    - docker ps -a

script:
    - docker exec --user 1000:1000 test_container bash ci/run_tests.sh
    - bash <(curl -s https://codecov.io/bash)
    # Want to make sure documentation can be successfully built
    - pip install .
    - bash ci/build_docs.sh

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs/_build/html
    target_branch: gh-pages
    email: "github-pages-deploy@travis-ci.org"
    on:
        branch: master
        python: "2.7"
