sudo: required

language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

install:
    - docker build -t pycondor_docker -f ci/Dockerfile --build-arg python_version=${TRAVIS_PYTHON_VERSION} .
    - docker run -d --name test_container pycondor_docker
    - docker ps -a

script:
    - docker exec test_container pytest --cov=pycondor pycondor
    - docker exec test_container flake8 pycondor
    - pip install .
    - bash ci/build_docs.sh

after_success:
    - docker exec test_container pip install codecov
    - ci_env=`bash <(curl -s https://codecov.io/env)`
    - docker exec test_container $ci_env; bash <(curl -s https://codecov.io/bash)

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs/_build/html
    target_branch: gh-pages
    email: "github-pages-deploy@travis-ci.org"
    on:
        branch: master
        python: "2.7"
