site_name: PyCondor
site_author: James Bourbeau
site_description: Python utility for HTCondor
copyright: Copyright &copy; 2017 <a href="https://jrbourbeau.github.io/">James Bourbeau</a>
pages:
    - Home: index.md
    - Installation: installation.md
    - API:
        - 'Job': Job.md
        - 'Dagman': Dagman.md
    - Examples : examples.md
    - Release notes : CHANGELOG.md
    - Contributing : contributing.md
repo_name: 'GitHub'
repo_url: https://github.com/jrbourbeau/pycondor
theme: material
extra:
    font:
        text: 'Roboto'
    palette:
        primary: 'green'
        accent: 'blue'
    social:
        - type: 'github'
          link: 'https://github.com/jrbourbeau'

markdown_extensions:
  - codehilite
  - toc(permalink=true)
