site_name: PyCondor
site_author: James Bourbeau
site_description: Python utility for HTCondor
# site_dir: ../docs
copyright: Copyright &copy; 2017 <a href="http://jamesbourbeau.com">James Bourbeau</a>
pages:
    - Home: index.md
    - Installation: installation.md
    - API:
        - 'Job': Job.md
        - 'Dagman': Dagman.md
    - Examples : examples.md
    - Release notes : CHANGELOG.md
repo_name: 'GitHub'
repo_url: https://github.com/jrbourbeau/pycondor
theme: material
theme_dir: 'mkdocs-material/material'
extra:
    font:
        text: 'Roboto'
    palette:
        primary: 'teal'
        accent: 'green'
    social:
        - type: 'github'
          link: 'https://github.com/jrbourbeau'
    logo: 'images/logo.png'

markdown_extensions:
  - codehilite
  - toc(permalink=true)
